# Generated by Django 3.1.2 on 2020-12-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201204_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='0000000000', max_length=10),
        ),
    ]
