# Generated by Django 3.1.2 on 2020-12-01 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20201201_2112'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='ChatGroup',
        ),
    ]
